"""add is_active column to category

Revision ID: ad8b0fb23e2b
Revises: 6d510c90a1f1
Create Date: 2026-06-27 00:55:53.820512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad8b0fb23e2b'
down_revision: Union[str, Sequence[str], None] = '6d510c90a1f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_active')
    # ### end Alembic commands ###
