"""turn name column in category and product table unique

Revision ID: c8e6efebe8c6
Revises: ad8b0fb23e2b
Create Date: 2026-06-27 18:55:04.138705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e6efebe8c6'
down_revision: Union[str, Sequence[str], None] = 'ad8b0fb23e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categories', ['name'])
    op.create_unique_constraint(None, 'products', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    # ### end Alembic commands ###
