"""alter user_type column default to USER value

Revision ID: f0d3a031ca4d
Revises: 8a055d96bbce
Create Date: 2026-07-05 13:07:34.597103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0d3a031ca4d'
down_revision: Union[str, Sequence[str], None] = '8a055d96bbce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Definimos los Enums
discount_enum = postgresql.ENUM('PERCENTAGE', 'FIXED_AMOUNT', 'FREE_SHIPPING', name='discounttypeenum')
order_status_enum = postgresql.ENUM('PENDING', 'APPROVED', 'PREPARING', 'SHIPPED', 'DELIVERED', 'CANCELED', name='orderstatusenum')
user_type_enum = postgresql.ENUM('INDIVIDUAL', 'COMPANY', 'ADMIN', name='usertypeenum')

def upgrade() -> None:
    # 1. Creamos los tipos ENUM en la base de datos PRIMERO
    discount_enum.create(op.get_bind(), checkfirst=True)
    user_type_enum.create(op.get_bind(), checkfirst=True)


    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bling_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_listings_bling_id'), 'product_listings', ['bling_id'], unique=True)
    
    op.create_table('listing_attributes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('bling_external_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('attribute_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['product_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('listing_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('bling_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('image_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['product_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('order_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('old_status', order_status_enum, nullable=True),
    sa.Column('new_status', order_status_enum, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.add_column('categories', sa.Column('bling_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_categories_bling_id'), 'categories', ['bling_id'], unique=True)
    
    # 2. Alteração do discount_type em coupons com postgresql_using
    op.alter_column('coupons', 'discount_type',
               existing_type=sa.VARCHAR(length=20),
               type_=discount_enum,
               existing_nullable=False,
               postgresql_using='discount_type::text::discounttypeenum')
               
    op.alter_column('coupons', 'discount_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('coupons', 'min_order_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.drop_constraint(op.f('coupons_code_key'), 'coupons', type_='unique')
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    
    op.alter_column('order_items', 'unit_price_snapshot',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
               
    # 3. Alteração do discount_type em orders com postgresql_using
    op.alter_column('orders', 'discount_type',
               existing_type=sa.VARCHAR(length=20),
               type_=discount_enum,
               existing_nullable=True,
               postgresql_using='discount_type::text::discounttypeenum')
               
    op.alter_column('orders', 'discount_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('orders', 'shipping_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('orders', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
               
    # 4. Alteração do status em orders com postgresql_using
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=order_status_enum,
               existing_nullable=False,
               postgresql_using='status::text::orderstatusenum')
               
    op.drop_constraint(op.f('orders_order_code_key'), 'orders', type_='unique')
    op.create_index(op.f('ix_orders_order_code'), 'orders', ['order_code'], unique=True)
    op.add_column('product_variants', sa.Column('bling_id', sa.Integer(), nullable=True))
    op.add_column('product_variants', sa.Column('bling_sku', sa.String(length=100), nullable=False))
    op.add_column('product_variants', sa.Column('variation_name', sa.String(length=100), nullable=False))
    op.add_column('product_variants', sa.Column('gtin', sa.String(length=50), nullable=True))
    op.add_column('product_variants', sa.Column('packaging_gtin', sa.String(length=50), nullable=True))
    op.add_column('product_variants', sa.Column('last_bling_sync', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('product_variants_sku_bling_key'), 'product_variants', type_='unique')
    op.create_index(op.f('ix_product_variants_bling_id'), 'product_variants', ['bling_id'], unique=True)
    op.create_unique_constraint(None, 'product_variants', ['bling_sku'])
    op.drop_column('product_variants', 'sku_bling')
    op.drop_column('product_variants', 'name_variation')
    op.drop_column('product_variants', 'last_sync_bling')
    op.add_column('products', sa.Column('bling_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('code', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('complementary_description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('product_type', sa.String(length=10), nullable=True))
    op.add_column('products', sa.Column('format', sa.String(length=10), nullable=True))
    op.add_column('products', sa.Column('status', sa.String(length=10), nullable=True))
    op.add_column('products', sa.Column('brand', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('condition', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('unit', sa.String(length=10), nullable=True))
    op.add_column('products', sa.Column('dimensions_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('inventory_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('media_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint(op.f('products_name_key'), 'products', type_='unique')
    op.create_index(op.f('ix_products_bling_id'), 'products', ['bling_id'], unique=True)
    op.create_unique_constraint(None, 'products', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_index(op.f('ix_products_bling_id'), table_name='products')
    op.create_unique_constraint(op.f('products_name_key'), 'products', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('products', 'custom_fields')
    op.drop_column('products', 'media_raw')
    op.drop_column('products', 'inventory_raw')
    op.drop_column('products', 'dimensions_raw')
    op.drop_column('products', 'unit')
    op.drop_column('products', 'condition')
    op.drop_column('products', 'brand')
    op.drop_column('products', 'status')
    op.drop_column('products', 'format')
    op.drop_column('products', 'product_type')
    op.drop_column('products', 'complementary_description')
    op.drop_column('products', 'code')
    op.drop_column('products', 'bling_id')
    op.add_column('product_variants', sa.Column('last_sync_bling', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('product_variants', sa.Column('name_variation', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('product_variants', sa.Column('sku_bling', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_variants', type_='unique')
    op.drop_index(op.f('ix_product_variants_bling_id'), table_name='product_variants')
    op.create_unique_constraint(op.f('product_variants_sku_bling_key'), 'product_variants', ['sku_bling'], postgresql_nulls_not_distinct=False)
    op.drop_column('product_variants', 'last_bling_sync')
    op.drop_column('product_variants', 'packaging_gtin')
    op.drop_column('product_variants', 'gtin')
    op.drop_column('product_variants', 'variation_name')
    op.drop_column('product_variants', 'bling_sku')
    op.drop_column('product_variants', 'bling_id')
    op.drop_index(op.f('ix_orders_order_code'), table_name='orders')
    op.create_unique_constraint(op.f('orders_order_code_key'), 'orders', ['order_code'], postgresql_nulls_not_distinct=False)
    
    op.alter_column('orders', 'status',
               existing_type=order_status_enum,
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               postgresql_using='status::text')
               
    op.alter_column('orders', 'total_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('orders', 'shipping_fee',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('orders', 'discount_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
               
    op.alter_column('orders', 'discount_type',
               existing_type=discount_enum,
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               postgresql_using='discount_type::text')
               
    op.alter_column('order_items', 'unit_price_snapshot',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.create_unique_constraint(op.f('coupons_code_key'), 'coupons', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('coupons', 'min_order_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('coupons', 'discount_value',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
               
    op.alter_column('coupons', 'discount_type',
               existing_type=discount_enum,
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               postgresql_using='discount_type::text')
               
    op.drop_index(op.f('ix_categories_bling_id'), table_name='categories')
    op.drop_column('categories', 'bling_id')
    op.drop_table('order_status_history')
    op.drop_table('listing_images')
    op.drop_table('listing_attributes')
    op.drop_index(op.f('ix_product_listings_bling_id'), table_name='product_listings')
    op.drop_table('product_listings')
    # ### end Alembic commands ###

    # Borramos los enums en el downgrade (solo después de revertir las tablas)
    discount_enum.drop(op.get_bind(), checkfirst=True)
    order_status_enum.drop(op.get_bind(), checkfirst=True)